
name: 1stAuction 
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  Auction:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current bid
        id: var
        run: |
          curl -H "project_id:  ${{ secrets.BLACKFROST }}" \
          "https://cardano-mainnet.blockfrost.io/api/v0/addresses/addr1v9r0g0n3jqshfdl932t0ytq3mupgt0cjut6lz9hdfvqse8sthxl7x" | jq '.amount[0].quantity|=tonumber / 1000000 - 2' > test.txt 
          adabid=$(cat test.txt | jq '.amount[0].quantity') 
          echo "adabid=$adabid" >> $GITHUB_ENV
      - name: Export Variable
        uses: UnlyEd/github-action-store-variable@v2.1.0
        with:
          variables: |
            adabid=${{ env.adabid }}
      - name: import variable
        uses: UnlyEd/github-action-store-variable@v2.1.0
        with:
          variables: |
           adabid
      -  name: "Create issue for Bid"
         uses: dacbd/create-issue-action@v1
         
         with:
          token: ${{ github.token }}
          title: ${{ env.adabid }} ADA is the current bid
          body: ${{ env.adabid }} ADA is the current bid
     

    
          
 
          
    
    
        
 
